stages:
  - test
  - build

backend-tests:
  stage: test
  image: golang:1.22
  before_script:
    - cd backend
  script:
    - go test ./...

frontend-build:
  stage: test
  image: node:20
  before_script:
    - cd frontend
  script:
    - npm ci
    - npm run build

compose-build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose build
